name: lyre
version: 0.1.0.0
github: "Mozzius/lyre"
license: BSD3
author: "Samuel Newman"
maintainer: "samuel@felixnewman.com"
copyright: "2020 Samuel Newman"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

description: Please see the README on GitHub at <https://github.com/githubuser/lyre#readme>

dependencies:
  - base >= 4.7 && < 5
  - array
  - text
  - filepath

library:
  source-dirs: src

executables:
  lyre-exe:
    main: Main.hs
    source-dirs: .
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    build-tools:
      - alex
      - happy
    dependencies:
      - lyre
#
# tests:
#   lyre-test:
#     main: Spec.hs
#     source-dirs: test
#     ghc-options:
#       - -threaded
#       - -rtsopts
#       - -with-rtsopts=-N
#     dependencies:
#       - lyre
