name: lyre
version: 0.1.0
description: Lyre is a funcitonal programming language that compiles to Erlang, aiming to implement a channel-based concurrency system
github: "mozzius/lyre"
license: BSD3
author: "Samuel Newman"
maintainer: "mozzius@protonmail.com"
copyright: "2020 Samuel Newman"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

dependencies:
  - base >=4.14
  - array
  - text
  - filepath
  - CoreErlang ==0.0.5
  - process
  - directory

library:
  source-dirs: src

executables:
  lyre-exe:
    main: src/Main.hs
    source-dirs: .
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    build-tools:
      - alex
      - happy
    dependencies:
      - lyre
#
# tests:
#   lyre-test:
#     main: Spec.hs
#     source-dirs: test
#     ghc-options:
#       - -threaded
#       - -rtsopts
#       - -with-rtsopts=-N
#     dependencies:
#       - lyre
